heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running the Open
  Source version of ownCloud.

parameter_groups:

- label: Server Settings
  parameters:
  - flavor
  - image

- label: ownCloud Settings
  parameters:
  - owncloud_username

- label: rax-dev-params
  parameters:
  - kitchen
  - chef_version

parameters:

  image:
    label: Operating System
    description: |
      Server image used for all servers that are created as a part of this
      deployment.
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
      description: Must be a supported operating system.

  flavor:
    label: Server Size
    description: |
      Rackspace Cloud Server flavor to use. The size is based on the amount of
      RAM for the provisioned server.
    type: string
    default: 2 GB General Purpose v1
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
      - 15 GB I/O v1
      - 30 GB I/O v1
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  owncloud_username:
    label: Username
    description: Username to use when logging into ownCloud
    type: string
    default: admin
    constraints:
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  kitchen:
    label: Kitchen
    description: URL for the kitchen to use
    type: string
    default: https://github.com/rackspace-orchestration-templates/owncloud

  chef_version:
    label: Chef Version
    description: Version of chef client to use
    type: string
    default: 11.12.8

resources:
  # Password Generation
  owncloud_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  owncloud_db_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  mysql_root_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  mysql_repl_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  mysql_debian_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  # SSH key
  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  owncloud_server:
    type: "OS::Nova::Server"
    properties:
      name: ownCloud
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
      config_drive: "true"
      user_data_format: RAW
      user_data: |
        #cloud-config
        apt_sources:
         - source: "ppa:ondrej/php5-oldstable"
        package_update: true

  owncloud_server_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: owncloud_server
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [owncloud_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        mysql:
          server_debian_password: { get_attr: [mysql_debian_password, value] }
          server_repl_password: { get_attr: [mysql_repl_password, value] }
          server_root_password: { get_attr: [mysql_root_password, value] }
        owncloud:
          admin:
            user: { get_param: owncloud_username }
            pass: { get_attr: [owncloud_password, value] }
          server_aliases:
            - { get_attr: [owncloud_server, accessIPv4] }
          config:
            dbpassword: { get_attr: [owncloud_db_password, value] }
        rax:
          firewall:
            tcp: [ 80, 443 ]
        run_list: ["recipe[apt]",
                   "recipe[owncloud]",
                   "recipe[rax-firewall]"]

outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }
    description: "SSH Private Key"

  server_ip:
    value: { get_attr: [owncloud_server, accessIPv4] }
    description: "Server IP"

  owncloud_url:
    value:
      str_replace:
        template: "https://%server_ip%"
        params:
          "%server_ip%": { get_attr: [owncloud_server, accessIPv4] }
    description: "ownCloud URL"

  owncloud_username:
    value: { get_param: owncloud_username }
    description: "ownCloud Username"

  owncloud_password:
    value: { get_attr: [owncloud_password, value] }
    description: "ownCloud Password"
